const players = [
  {
    name: 'Nikola Jokic',
    overall: 98,
    ballHandling: 87,
    threePoint: 92,
    midRange: 88,
    freeThrow: 83,
    drivingLayup: 90,
    drivingDunk: 75,
    standingDunk: 80,
  },
  {
    name: 'Giannis Antetokounmpo',
    overall: 98,
    ballHandling: 86,
    threePoint: 72,
    midRange: 79,
    freeThrow: 65,
    drivingLayup: 98,
    drivingDunk: 97,
    standingDunk: 95,
  },
  {
    name: 'Shai Gilgeous-Alexander',
    overall: 98,
    ballHandling: 94,
    threePoint: 85,
    midRange: 90,
    freeThrow: 88,
    drivingLayup: 97,
    drivingDunk: 75,
    standingDunk: 40,
  },
  {
    name: 'Luka Doncic',
    overall: 96,
    ballHandling: 92,
    threePoint: 88,
    midRange: 84,
    freeThrow: 80,
    drivingLayup: 95,
    drivingDunk: 74,
    standingDunk: 64,
  },
  {
    name: 'LeBron James',
    overall: 96,
    ballHandling: 86,
    threePoint: 85,
    midRange: 88,
    freeThrow: 73,
    drivingLayup: 98,
    drivingDunk: 89,
    standingDunk: 80,
  },
  {
    name: 'Stephen Curry',
    overall: 95,
    ballHandling: 97,
    threePoint: 99,
    midRange: 95,
    freeThrow: 92,
    drivingLayup: 96,
    drivingDunk: 36,
    standingDunk: 25,
  },
  {
    name: 'Jayson Tatum',
    overall: 95,
    ballHandling: 86,
    threePoint: 88,
    midRange: 90,
    freeThrow: 85,
    drivingLayup: 96,
    drivingDunk: 89,
    standingDunk: 50,
  },
  {
    name: 'Kevin Durant',
    overall: 95,
    ballHandling: 89,
    threePoint: 89,
    midRange: 97,
    freeThrow: 88,
    drivingLayup: 96,
    drivingDunk: 85,
    standingDunk: 60,
  },
  {
    name: 'Anthony Davis',
    overall: 95,
    ballHandling: 79,
    threePoint: 75,
    midRange: 85,
    freeThrow: 80,
    drivingLayup: 90,
    drivingDunk: 90,
    standingDunk: 95,
  },
  {
    name: 'Joel Embiid',
    overall: 95,
    ballHandling: 70,
    threePoint: 80,
    midRange: 88,
    freeThrow: 85,
    drivingLayup: 89,
    drivingDunk: 80,
    standingDunk: 90,
  },
  {
    name: 'Michael Jordan',
    overall: 99,
    ballHandling: 95,
    threePoint: 78,
    midRange: 99,
    freeThrow: 85,
    drivingLayup: 99,
    drivingDunk: 98,
    standingDunk: 75,
  },
  {
    name: 'Kobe Bryant',
    overall: 98,
    ballHandling: 95,
    threePoint: 85,
    midRange: 98,
    freeThrow: 84,
    drivingLayup: 98,
    drivingDunk: 95,
    standingDunk: 70,
  },
  {
    name: 'Magic Johnson',
    overall: 99,
    ballHandling: 98,
    threePoint: 79,
    midRange: 86,
    freeThrow: 84,
    drivingLayup: 97,
    drivingDunk: 65,
    standingDunk: 55,
  },
  {
    name: 'Larry Bird',
    overall: 98,
    ballHandling: 84,
    threePoint: 98,
    midRange: 99,
    freeThrow: 92,
    drivingLayup: 90,
    drivingDunk: 55,
    standingDunk: 50,
  },
  {
    name: "Shaquille O'Neal",
    overall: 98,
    ballHandling: 60,
    threePoint: 50,
    midRange: 65,
    freeThrow: 53,
    drivingLayup: 85,
    drivingDunk: 98,
    standingDunk: 99,
  },
  {
    name: 'Wilt Chamberlain',
    overall: 99,
    ballHandling: 68,
    threePoint: 55,
    midRange: 75,
    freeThrow: 58,
    drivingLayup: 97,
    drivingDunk: 99,
    standingDunk: 99,
  },
  {
    name: 'Tim Duncan',
    overall: 98,
    ballHandling: 75,
    threePoint: 70,
    midRange: 90,
    freeThrow: 79,
    drivingLayup: 85,
    drivingDunk: 80,
    standingDunk: 95,
  },
  {
    name: 'Hakeem Olajuwon',
    overall: 98,
    ballHandling: 78,
    threePoint: 72,
    midRange: 87,
    freeThrow: 78,
    drivingLayup: 88,
    drivingDunk: 85,
    standingDunk: 95,
  },
  {
    name: 'Dirk Nowitzki',
    overall: 97,
    ballHandling: 76,
    threePoint: 96,
    midRange: 99,
    freeThrow: 89,
    drivingLayup: 85,
    drivingDunk: 70,
    standingDunk: 80,
  },
  {
    name: 'Oscar Robertson',
    overall: 97,
    ballHandling: 95,
    threePoint: 80,
    midRange: 90,
    freeThrow: 85,
    drivingLayup: 97,
    drivingDunk: 75,
    standingDunk: 60,
  },
  {
    name: 'Jimmy Butler',
    overall: 94,
    ballHandling: 86,
    threePoint: 82,
    midRange: 88,
    freeThrow: 85,
    drivingLayup: 96,
    drivingDunk: 80,
    standingDunk: 50,
  },
  {
    name: 'Devin Booker',
    overall: 94,
    ballHandling: 90,
    threePoint: 89,
    midRange: 94,
    freeThrow: 91,
    drivingLayup: 95,
    drivingDunk: 75,
    standingDunk: 40,
  },
  {
    name: 'Damian Lillard',
    overall: 93,
    ballHandling: 96,
    threePoint: 97,
    midRange: 90,
    freeThrow: 91,
    drivingLayup: 94,
    drivingDunk: 80,
    standingDunk: 35,
  },
  {
    name: 'Ja Morant',
    overall: 93,
    ballHandling: 97,
    threePoint: 82,
    midRange: 85,
    freeThrow: 79,
    drivingLayup: 98,
    drivingDunk: 97,
    standingDunk: 65,
  },
  {
    name: 'Kawhi Leonard',
    overall: 93,
    ballHandling: 86,
    threePoint: 85,
    midRange: 94,
    freeThrow: 88,
    drivingLayup: 95,
    drivingDunk: 85,
    standingDunk: 60,
  },
  {
    name: 'Donovan Mitchell',
    overall: 92,
    ballHandling: 94,
    threePoint: 88,
    midRange: 86,
    freeThrow: 87,
    drivingLayup: 96,
    drivingDunk: 92,
    standingDunk: 55,
  },
  {
    name: 'Zion Williamson',
    overall: 92,
    ballHandling: 83,
    threePoint: 78,
    midRange: 80,
    freeThrow: 72,
    drivingLayup: 97,
    drivingDunk: 99,
    standingDunk: 98,
  },
  {
    name: 'Jaylen Brown',
    overall: 91,
    ballHandling: 86,
    threePoint: 85,
    midRange: 88,
    freeThrow: 80,
    drivingLayup: 94,
    drivingDunk: 92,
    standingDunk: 60,
  },
  {
    name: 'Tyrese Haliburton',
    overall: 91,
    ballHandling: 95,
    threePoint: 90,
    midRange: 85,
    freeThrow: 89,
    drivingLayup: 92,
    drivingDunk: 70,
    standingDunk: 35,
  },
  {
    name: 'James Harden',
    overall: 90,
    ballHandling: 97,
    threePoint: 87,
    midRange: 90,
    freeThrow: 86,
    drivingLayup: 94,
    drivingDunk: 70,
    standingDunk: 40,
  },
  {
    name: 'Kyrie Irving',
    overall: 94,
    ballHandling: 99,
    threePoint: 90,
    midRange: 97,
    freeThrow: 91,
    drivingLayup: 99,
    drivingDunk: 60,
    standingDunk: 30,
  },
  {
    name: 'Paul George',
    overall: 93,
    ballHandling: 88,
    threePoint: 89,
    midRange: 92,
    freeThrow: 85,
    drivingLayup: 95,
    drivingDunk: 90,
    standingDunk: 65,
  },
  {
    name: 'Jrue Holiday',
    overall: 92,
    ballHandling: 88,
    threePoint: 85,
    midRange: 84,
    freeThrow: 83,
    drivingLayup: 90,
    drivingDunk: 75,
    standingDunk: 40,
  },
  {
    name: 'Bam Adebayo',
    overall: 91,
    ballHandling: 78,
    threePoint: 70,
    midRange: 82,
    freeThrow: 76,
    drivingLayup: 90,
    drivingDunk: 85,
    standingDunk: 95,
  },
  {
    name: 'Jamal Murray',
    overall: 91,
    ballHandling: 92,
    threePoint: 88,
    midRange: 90,
    freeThrow: 87,
    drivingLayup: 95,
    drivingDunk: 75,
    standingDunk: 40,
  },
  {
    name: 'Anthony Edwards',
    overall: 90,
    ballHandling: 89,
    threePoint: 86,
    midRange: 85,
    freeThrow: 80,
    drivingLayup: 96,
    drivingDunk: 98,
    standingDunk: 75,
  },
  {
    name: "De'Aaron Fox",
    overall: 90,
    ballHandling: 94,
    threePoint: 84,
    midRange: 88,
    freeThrow: 79,
    drivingLayup: 98,
    drivingDunk: 85,
    standingDunk: 50,
  },
  {
    name: 'Brandon Ingram',
    overall: 90,
    ballHandling: 88,
    threePoint: 86,
    midRange: 90,
    freeThrow: 85,
    drivingLayup: 94,
    drivingDunk: 85,
    standingDunk: 50,
  },
  {
    name: 'Domantas Sabonis',
    overall: 90,
    ballHandling: 80,
    threePoint: 72,
    midRange: 85,
    freeThrow: 75,
    drivingLayup: 92,
    drivingDunk: 82,
    standingDunk: 90,
  },
  {
    name: 'Karl-Anthony Towns',
    overall: 90,
    ballHandling: 79,
    threePoint: 88,
    midRange: 86,
    freeThrow: 83,
    drivingLayup: 90,
    drivingDunk: 85,
    standingDunk: 95,
  },
  {
    name: 'Kristaps Porzingis',
    overall: 89,
    ballHandling: 72,
    threePoint: 85,
    midRange: 88,
    freeThrow: 82,
    drivingLayup: 85,
    drivingDunk: 80,
    standingDunk: 95,
  },
  {
    name: 'Mikal Bridges',
    overall: 89,
    ballHandling: 84,
    threePoint: 88,
    midRange: 85,
    freeThrow: 83,
    drivingLayup: 92,
    drivingDunk: 80,
    standingDunk: 55,
  },
  {
    name: 'Jaren Jackson Jr.',
    overall: 89,
    ballHandling: 75,
    threePoint: 82,
    midRange: 80,
    freeThrow: 79,
    drivingLayup: 88,
    drivingDunk: 90,
    standingDunk: 95,
  },
  {
    name: 'Julius Randle',
    overall: 88,
    ballHandling: 82,
    threePoint: 80,
    midRange: 85,
    freeThrow: 76,
    drivingLayup: 90,
    drivingDunk: 85,
    standingDunk: 80,
  },
  {
    name: 'CJ McCollum',
    overall: 88,
    ballHandling: 88,
    threePoint: 86,
    midRange: 90,
    freeThrow: 82,
    drivingLayup: 94,
    drivingDunk: 60,
    standingDunk: 30,
  },
  {
    name: 'Darius Garland',
    overall: 88,
    ballHandling: 94,
    threePoint: 88,
    midRange: 87,
    freeThrow: 85,
    drivingLayup: 92,
    drivingDunk: 65,
    standingDunk: 25,
  },
  {
    name: 'Fred VanVleet',
    overall: 88,
    ballHandling: 90,
    threePoint: 88,
    midRange: 85,
    freeThrow: 85,
    drivingLayup: 92,
    drivingDunk: 55,
    standingDunk: 20,
  },
  {
    name: 'Desmond Bane',
    overall: 87,
    ballHandling: 86,
    threePoint: 89,
    midRange: 84,
    freeThrow: 83,
    drivingLayup: 90,
    drivingDunk: 75,
    standingDunk: 35,
  },
  {
    name: 'Jalen Brunson',
    overall: 87,
    ballHandling: 90,
    threePoint: 85,
    midRange: 90,
    freeThrow: 86,
    drivingLayup: 96,
    drivingDunk: 60,
    standingDunk: 30,
  },
  {
    name: 'Pascal Siakam',
    overall: 87,
    ballHandling: 80,
    threePoint: 78,
    midRange: 82,
    freeThrow: 79,
    drivingLayup: 94,
    drivingDunk: 85,
    standingDunk: 75,
  },
  {
    name: 'Brook Lopez',
    overall: 87,
    ballHandling: 68,
    threePoint: 83,
    midRange: 85,
    freeThrow: 78,
    drivingLayup: 85,
    drivingDunk: 80,
    standingDunk: 95,
  },
  {
    name: 'Tyrese Maxey',
    overall: 86,
    ballHandling: 90,
    threePoint: 88,
    midRange: 86,
    freeThrow: 85,
    drivingLayup: 94,
    drivingDunk: 75,
    standingDunk: 30,
  },
  {
    name: 'Jaden Ivey',
    overall: 86,
    ballHandling: 88,
    threePoint: 82,
    midRange: 80,
    freeThrow: 78,
    drivingLayup: 92,
    drivingDunk: 90,
    standingDunk: 50,
  },
  {
    name: 'Aaron Gordon',
    overall: 86,
    ballHandling: 78,
    threePoint: 80,
    midRange: 78,
    freeThrow: 75,
    drivingLayup: 88,
    drivingDunk: 97,
    standingDunk: 98,
  },
  {
    name: 'Deandre Ayton',
    overall: 86,
    ballHandling: 75,
    threePoint: 70,
    midRange: 85,
    freeThrow: 75,
    drivingLayup: 85,
    drivingDunk: 85,
    standingDunk: 95,
  },
  {
    name: 'Kyle Kuzma',
    overall: 85,
    ballHandling: 80,
    threePoint: 82,
    midRange: 85,
    freeThrow: 79,
    drivingLayup: 92,
    drivingDunk: 85,
    standingDunk: 60,
  },
  {
    name: 'Franz Wagner',
    overall: 85,
    ballHandling: 84,
    threePoint: 83,
    midRange: 85,
    freeThrow: 82,
    drivingLayup: 92,
    drivingDunk: 80,
    standingDunk: 50,
  },
  {
    name: 'Scoot Henderson',
    overall: 85,
    ballHandling: 92,
    threePoint: 80,
    midRange: 85,
    freeThrow: 80,
    drivingLayup: 95,
    drivingDunk: 85,
    standingDunk: 50,
  },
  {
    name: 'Miles Bridges',
    overall: 85,
    ballHandling: 80,
    threePoint: 84,
    midRange: 82,
    freeThrow: 78,
    drivingLayup: 90,
    drivingDunk: 96,
    standingDunk: 75,
  },
  {
    name: 'Alperen Sengun',
    overall: 85,
    ballHandling: 78,
    threePoint: 75,
    midRange: 80,
    freeThrow: 77,
    drivingLayup: 88,
    drivingDunk: 80,
    standingDunk: 95,
  },
  {
    name: 'Austin Reaves',
    overall: 85,
    ballHandling: 86,
    threePoint: 85,
    midRange: 84,
    freeThrow: 86,
    drivingLayup: 90,
    drivingDunk: 70,
    standingDunk: 35,
  },
  {
    name: 'Jordan Poole',
    overall: 85,
    ballHandling: 90,
    threePoint: 86,
    midRange: 84,
    freeThrow: 87,
    drivingLayup: 92,
    drivingDunk: 75,
    standingDunk: 40,
  },
  {
    name: 'RJ Barrett',
    overall: 84,
    ballHandling: 82,
    threePoint: 79,
    midRange: 80,
    freeThrow: 75,
    drivingLayup: 94,
    drivingDunk: 88,
    standingDunk: 55,
  },
  {
    name: 'Anfernee Simons',
    overall: 84,
    ballHandling: 88,
    threePoint: 88,
    midRange: 85,
    freeThrow: 84,
    drivingLayup: 90,
    drivingDunk: 80,
    standingDunk: 45,
  },
  {
    name: 'Tobias Harris',
    overall: 84,
    ballHandling: 80,
    threePoint: 82,
    midRange: 84,
    freeThrow: 79,
    drivingLayup: 92,
    drivingDunk: 82,
    standingDunk: 60,
  },
  {
    name: 'Malik Monk',
    overall: 84,
    ballHandling: 86,
    threePoint: 85,
    midRange: 84,
    freeThrow: 82,
    drivingLayup: 90,
    drivingDunk: 85,
    standingDunk: 50,
  },
  {
    name: 'Josh Giddey',
    overall: 83,
    ballHandling: 88,
    threePoint: 79,
    midRange: 82,
    freeThrow: 76,
    drivingLayup: 92,
    drivingDunk: 70,
    standingDunk: 40,
  },
  {
    name: 'Buddy Hield',
    overall: 83,
    ballHandling: 82,
    threePoint: 90,
    midRange: 85,
    freeThrow: 86,
    drivingLayup: 85,
    drivingDunk: 60,
    standingDunk: 30,
  },
  {
    name: 'Tyus Jones',
    overall: 83,
    ballHandling: 90,
    threePoint: 84,
    midRange: 83,
    freeThrow: 88,
    drivingLayup: 89,
    drivingDunk: 50,
    standingDunk: 20,
  },
  {
    name: 'Jabari Smith Jr.',
    overall: 83,
    ballHandling: 78,
    threePoint: 84,
    midRange: 83,
    freeThrow: 81,
    drivingLayup: 88,
    drivingDunk: 80,
    standingDunk: 75,
  },
  {
    name: 'Jonas Valanciunas',
    overall: 83,
    ballHandling: 68,
    threePoint: 74,
    midRange: 80,
    freeThrow: 81,
    drivingLayup: 85,
    drivingDunk: 80,
    standingDunk: 95,
  },
  {
    name: 'Herbert Jones',
    overall: 82,
    ballHandling: 76,
    threePoint: 82,
    midRange: 80,
    freeThrow: 77,
    drivingLayup: 85,
    drivingDunk: 85,
    standingDunk: 60,
  },
  {
    name: 'Dillon Brooks',
    overall: 82,
    ballHandling: 78,
    threePoint: 80,
    midRange: 82,
    freeThrow: 80,
    drivingLayup: 88,
    drivingDunk: 82,
    standingDunk: 55,
  },
  {
    name: 'Markelle Fultz',
    overall: 82,
    ballHandling: 88,
    threePoint: 76,
    midRange: 80,
    freeThrow: 72,
    drivingLayup: 94,
    drivingDunk: 85,
    standingDunk: 50,
  },
  {
    name: 'Jalen Suggs',
    overall: 81,
    ballHandling: 84,
    threePoint: 79,
    midRange: 80,
    freeThrow: 78,
    drivingLayup: 90,
    drivingDunk: 85,
    standingDunk: 50,
  },
  {
    name: 'Bojan Bogdanovic',
    overall: 81,
    ballHandling: 78,
    threePoint: 86,
    midRange: 84,
    freeThrow: 85,
    drivingLayup: 88,
    drivingDunk: 70,
    standingDunk: 45,
  },
  {
    name: 'Mitchell Robinson',
    overall: 81,
    ballHandling: 60,
    threePoint: 50,
    midRange: 65,
    freeThrow: 55,
    drivingLayup: 75,
    drivingDunk: 90,
    standingDunk: 98,
  },
  {
    name: 'Norman Powell',
    overall: 81,
    ballHandling: 82,
    threePoint: 85,
    midRange: 83,
    freeThrow: 81,
    drivingLayup: 92,
    drivingDunk: 88,
    standingDunk: 55,
  },
  {
    name: 'Keldon Johnson',
    overall: 81,
    ballHandling: 80,
    threePoint: 82,
    midRange: 80,
    freeThrow: 78,
    drivingLayup: 90,
    drivingDunk: 85,
    standingDunk: 60,
  },
  {
    name: 'Bobby Portis',
    overall: 80,
    ballHandling: 72,
    threePoint: 80,
    midRange: 83,
    freeThrow: 78,
    drivingLayup: 85,
    drivingDunk: 75,
    standingDunk: 80,
  },
  {
    name: 'Deni Avdija',
    overall: 80,
    ballHandling: 76,
    threePoint: 78,
    midRange: 80,
    freeThrow: 74,
    drivingLayup: 85,
    drivingDunk: 80,
    standingDunk: 60,
  },
  {
    name: 'Clint Capela',
    overall: 80,
    ballHandling: 55,
    threePoint: 45,
    midRange: 60,
    freeThrow: 55,
    drivingLayup: 75,
    drivingDunk: 90,
    standingDunk: 98,
  },
  {
    name: 'Jusuf Nurkic',
    overall: 80,
    ballHandling: 70,
    threePoint: 60,
    midRange: 75,
    freeThrow: 70,
    drivingLayup: 85,
    drivingDunk: 78,
    standingDunk: 90,
  },
  {
    name: 'Josh Green',
    overall: 80,
    ballHandling: 78,
    threePoint: 81,
    midRange: 76,
    freeThrow: 75,
    drivingLayup: 85,
    drivingDunk: 85,
    standingDunk: 50,
  },
  {
    name: 'Kevon Looney',
    overall: 80,
    ballHandling: 60,
    threePoint: 45,
    midRange: 65,
    freeThrow: 68,
    drivingLayup: 75,
    drivingDunk: 80,
    standingDunk: 90,
  },
  {
    name: 'Jalen Smith',
    overall: 79,
    ballHandling: 65,
    threePoint: 78,
    midRange: 76,
    freeThrow: 74,
    drivingLayup: 80,
    drivingDunk: 85,
    standingDunk: 90,
  },
  {
    name: 'Dyson Daniels',
    overall: 79,
    ballHandling: 80,
    threePoint: 75,
    midRange: 78,
    freeThrow: 74,
    drivingLayup: 85,
    drivingDunk: 80,
    standingDunk: 50,
  },
  {
    name: 'Cole Anthony',
    overall: 79,
    ballHandling: 85,
    threePoint: 80,
    midRange: 80,
    freeThrow: 82,
    drivingLayup: 90,
    drivingDunk: 82,
    standingDunk: 40,
  },
  {
    name: 'Marvin Bagley III',
    overall: 79,
    ballHandling: 70,
    threePoint: 75,
    midRange: 78,
    freeThrow: 70,
    drivingLayup: 85,
    drivingDunk: 90,
    standingDunk: 95,
  },
  {
    name: 'Duncan Robinson',
    overall: 78,
    ballHandling: 75,
    threePoint: 88,
    midRange: 82,
    freeThrow: 86,
    drivingLayup: 75,
    drivingDunk: 60,
    standingDunk: 30,
  },
  {
    name: 'Tari Eason',
    overall: 78,
    ballHandling: 72,
    threePoint: 78,
    midRange: 75,
    freeThrow: 74,
    drivingLayup: 82,
    drivingDunk: 85,
    standingDunk: 70,
  },
  {
    name: 'Ziaire Williams',
    overall: 78,
    ballHandling: 76,
    threePoint: 79,
    midRange: 77,
    freeThrow: 75,
    drivingLayup: 83,
    drivingDunk: 82,
    standingDunk: 60,
  },
  {
    name: 'Payton Pritchard',
    overall: 78,
    ballHandling: 84,
    threePoint: 85,
    midRange: 81,
    freeThrow: 83,
    drivingLayup: 80,
    drivingDunk: 50,
    standingDunk: 20,
  },
  {
    name: 'Patrick Williams',
    overall: 77,
    ballHandling: 74,
    threePoint: 78,
    midRange: 75,
    freeThrow: 76,
    drivingLayup: 80,
    drivingDunk: 85,
    standingDunk: 75,
  },
  {
    name: 'Isaiah Stewart',
    overall: 77,
    ballHandling: 70,
    threePoint: 75,
    midRange: 72,
    freeThrow: 73,
    drivingLayup: 78,
    drivingDunk: 80,
    standingDunk: 90,
  },
  {
    name: 'Dario Saric',
    overall: 77,
    ballHandling: 76,
    threePoint: 80,
    midRange: 78,
    freeThrow: 80,
    drivingLayup: 82,
    drivingDunk: 70,
    standingDunk: 60,
  },
  {
    name: 'T.J. McConnell',
    overall: 77,
    ballHandling: 86,
    threePoint: 74,
    midRange: 78,
    freeThrow: 78,
    drivingLayup: 88,
    drivingDunk: 50,
    standingDunk: 20,
  },
  {
    name: 'Jevon Carter',
    overall: 76,
    ballHandling: 80,
    threePoint: 80,
    midRange: 75,
    freeThrow: 79,
    drivingLayup: 78,
    drivingDunk: 60,
    standingDunk: 25,
  },
  {
    name: 'Gabe Vincent',
    overall: 76,
    ballHandling: 78,
    threePoint: 81,
    midRange: 77,
    freeThrow: 76,
    drivingLayup: 80,
    drivingDunk: 65,
    standingDunk: 30,
  },
  {
    name: 'Mason Plumlee',
    overall: 76,
    ballHandling: 65,
    threePoint: 50,
    midRange: 65,
    freeThrow: 55,
    drivingLayup: 75,
    drivingDunk: 85,
    standingDunk: 95,
  },
  {
    name: 'Cam Reddish',
    overall: 75,
    ballHandling: 75,
    threePoint: 78,
    midRange: 76,
    freeThrow: 74,
    drivingLayup: 85,
    drivingDunk: 85,
    standingDunk: 55,
  },
  {
    name: 'Malaki Branham',
    overall: 75,
    ballHandling: 76,
    threePoint: 79,
    midRange: 78,
    freeThrow: 76,
    drivingLayup: 82,
    drivingDunk: 80,
    standingDunk: 50,
  },
  {
    name: 'Blake Wesley',
    overall: 75,
    ballHandling: 78,
    threePoint: 75,
    midRange: 75,
    freeThrow: 74,
    drivingLayup: 85,
    drivingDunk: 80,
    standingDunk: 50,
  },
]
